server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 301 /styleguide/;
    }

    location /styleguide/ {
        try_files $uri $uri/ /styleguide/index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
