server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;

    location = / {
        return 301 /styleguide/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
