types {
    text/html                             html htm;
    text/css                              css;
    text/javascript                       js mjs;
    application/json                      json;
    image/svg+xml                         svg svgz;
    image/png                             png;
    image/jpeg                            jpg jpeg;
    image/gif                             gif;
    image/webp                            webp;
    font/woff2                            woff2;
    font/woff                             woff;
    application/font-sfnt                 otf ttf;
}

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 301 /styleguide/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
